/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rubens
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Cadastrar = new javax.swing.JMenu();
        CadCliente = new javax.swing.JMenuItem();
        CadAnimal = new javax.swing.JMenuItem();
        AgendarServico = new javax.swing.JMenu();
        AgendarBanhoTosa = new javax.swing.JMenuItem();
        AgendarVacinacao = new javax.swing.JMenuItem();
        AgendarConsulta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Banho e Tosa", "09/03/21", "Maria", "Rex"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Serviço", "Data", "Cliente", "Pet"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Agenda");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CORA.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/PETS.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Pet Shop");

        Cadastrar.setText("Cadastrar");
        Cadastrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        CadCliente.setText("Cadastrar Cliente");
        CadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadClienteActionPerformed(evt);
            }
        });
        Cadastrar.add(CadCliente);

        CadAnimal.setText("Cadastrar Animal");
        CadAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadAnimalActionPerformed(evt);
            }
        });
        Cadastrar.add(CadAnimal);

        jMenuBar1.add(Cadastrar);

        AgendarServico.setText("Agendar Serviço");
        AgendarServico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        AgendarBanhoTosa.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AgendarBanhoTosa.setText("Banho e Tosa");
        AgendarBanhoTosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendarBanhoTosaActionPerformed(evt);
            }
        });
        AgendarServico.add(AgendarBanhoTosa);

        AgendarVacinacao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AgendarVacinacao.setText("Vacinação");
        AgendarServico.add(AgendarVacinacao);

        AgendarConsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AgendarConsulta.setText("Consulta");
        AgendarServico.add(AgendarConsulta);

        jMenuBar1.add(AgendarServico);

        jMenu4.setText("Efetuar Venda");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Estoque");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addGap(67, 67, 67))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void AgendarBanhoTosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendarBanhoTosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgendarBanhoTosaActionPerformed

    private void CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteActionPerformed
        CadastrarCliente cadCli = new CadastrarCliente();
        cadCli.setVisible(true);
    }//GEN-LAST:event_CadClienteActionPerformed

    private void CadAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadAnimalActionPerformed
        CadastrarAnimal cadAni = new CadastrarAnimal();
        cadAni.setVisible(true);
    }//GEN-LAST:event_CadAnimalActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgendarBanhoTosa;
    private javax.swing.JMenuItem AgendarConsulta;
    private javax.swing.JMenu AgendarServico;
    private javax.swing.JMenuItem AgendarVacinacao;
    private javax.swing.JMenuItem CadAnimal;
    private javax.swing.JMenuItem CadCliente;
    private javax.swing.JMenu Cadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
